### ISSUE TITLE
Need the code for hardhat method deployment

### ISSUE THREAD

**Issue by harshnambiar** [Metis-DAO/Metis#2]
Hardhat has updated and now when you run "npx hardhat" there is no option for "advanced project". It would be nice if you could provide the complete code to new users like me, because it's almost impossible to reconstruct it just from the glimpses you have shown in the .md file.

**Comment by harshnambiar** [comment]
Downgrading the hardhat version to 2.9.9 did the trick, but would still like people access to the code so here it is:
https://github.com/harshnambiar/namaste_metis

**Comment by TheVictorMunoz** [comment]
@0x000hx any idea on why do we need to downgrade to hardhat 2.9.9 ?
